name: Jacky Test
favicon: null
layout_spectrum: 0.22713
typography_spectrum: 0.55107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
