name: Jacky Test
favicon: null
layout_spectrum: 0.6022370967548341
typography_spectrum: 0.835805966053158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7444400291424245
  lightness: 0.21233650925569236
  saturation: 0.041481210850179195
  rhythmicContrast: 0.9024500011000782
purpose: []
